colour: colour.cpp
	g++ -std=c++11 colour.cpp -o colour -I/opt/ibm/ILOG/CPLEX_Studio127/cplex/include/ -I/opt/ibm/ILOG/CPLEX_Studio127/concert/include/ -DIL_STD -L/opt/ibm/ILOG/CPLEX_Studio127/cplex/lib/x86-64_linux/static_pic -L/opt/ibm/ILOG/CPLEX_Studio127/concert/lib/x86-64_linux/static_pic -lilocplex -lconcert -lcplex -lm -lpthread -lstdc++fs  -O3
	rm -f *.o
